;source: old Library
delimiters =	" " / "" / "!" / "@" / "#" / "$" / "%" / "^" / "&" / "*" / "(" / ")" / "-" / "+" / "=" / ":" / ";" / "'" / "\" / "/" / "?" / "." / "," / 
				"\\" / "\x0D" / "\X0A" / "\x09" / "\x3C" / "\3E"
				2*2"\x09" / 100*100"\x09" / 100*100"\x09\x0D\0A" / 100*100":" / 100*100":7" / 64*64"\x0D\x0A" / 128*128"\x0D\x0A" / 512*512"\x0D\x0A"
